const test=require('node:test'),assert=require('node:assert/strict');
const M=require('../public/domain.js'),R=require('../public/reusable-rules.js'),{appHarness}=require('./app-harness.cjs');
function seeded(){const s=M.seed();s.records=[];s.active=s.plans[0].id;s.activeShop=s.plans[0].shopId;const m=s.materials.find(x=>x.weightRules?.some(r=>r.default));s.plans[0].materialId=m.id;s.plans[0].materialRuleId=m.weightRules.find(r=>r.default).id;return s;}
function click(dispatch,action,more={}){return dispatch('click',{closest:()=>({dataset:{action,...more}})});}
test('添加规格只列未用常规尺寸，提交只追加，取消不建公共尺寸',()=>{const s=seeded(),h=appHarness(s),p=s.plans[0],before=M.clone(p.items),candidate=s.sizes.find(x=>!x.irregular&&!p.items.some(i=>i.sizeId===x.id));h.ui.open('add-skus',{ids:[],draft:{salesW:'',salesH:''}});const html=h.elements.get('#dialog').innerHTML;assert.match(html,/自定义尺寸/);for(const key of ['data-plan-material','data-field="materialId"','data-field="price"','nested-size'])assert.ok(!html.includes(key));assert.ok(!h.ui.commonSizeChoices().includes('data-select-size="'+p.items[0].sizeId+'"'));if(candidate)h.ui.modal.ids.push(candidate.id);else Object.assign(h.ui.modal.draft,{salesW:31,salesH:47});h.ui.saveModal();assert.deepEqual(h.ui.state.plans[0].items.slice(0,before.length),before);assert.equal(h.ui.state.plans[0].items.length,before.length+1);const count=h.ui.state.sizes.length;h.ui.open('add-skus',{ids:[],draft:{salesW:33,salesH:71}});h.ui.close(true);assert.equal(h.ui.state.sizes.length,count);});
test('删除默认规则后添加规格不能偷偷回退，输入保留且工作区不变',()=>{const s=seeded(),p=s.plans[0];s.materials.find(x=>x.id===p.materialId).deleted=true;const h=appHarness(s),before=M.clone(s);h.ui.open('add-skus',{ids:[],draft:{salesW:33,salesH:71}});h.ui.saveModal();assert.deepEqual(h.ui.state,before);assert.equal(h.ui.modal.type,'add-skus');assert.match(h.elements.get('#dialog-error').textContent,/默认材料/);});
test('非法新规则不污染状态，合法规则可保存',()=>{const h=appHarness(seeded()),before=M.clone(h.ui.state);h.ui.open('reusable',{kind:'pricingStrategies',draft:{name:'无效',type:'uniform',margin:110}});assert.throws(()=>h.ui.saveModal());assert.deepEqual(h.ui.state,before);h.ui.modal.draft.margin=30;h.ui.saveModal();assert.equal(h.ui.state.pricingStrategies[0].margin,30);assert.ok(M.validateBackup(h.ui.state));});
test('复制库中尺寸方案复制原方案，和当前计划尺寸无关',()=>{let s=seeded();s=R.save(s,'sizeSchemes',{name:'源组合',sizeIds:[s.sizes.at(-1).id]});const h=appHarness(s),source=s.sizeSchemes[0];h.ui.open('save-rule-copy',{kind:'sizeSchemes',sourceId:source.id,draft:{name:'副本'}});h.ui.saveModal();assert.deepEqual(h.ui.state.sizeSchemes[1].sizeIds,source.sizeIds);});
test('同尺寸两行以 item.id 精确改价，非法价格不写保存队列',async()=>{const s=seeded(),p=s.plans[0];p.items.push({...M.clone(p.items[0]),id:'second-row'});const h=appHarness(s);let writes=0;h.ui.queue={enqueue(){writes++;}};const el={type:'number',value:'22.50',dataset:{item:'second-row',key:'price'},matches:x=>x==='[data-item]',setAttribute(){},removeAttribute(){}};await h.dispatch('input',el);assert.equal(h.ui.state.plans[0].items.at(-1).price,22.5);assert.equal(h.ui.state.plans[0].items.at(-1).priceMode,'manual');assert.equal(h.ui.state.plans[0].items[0].price,p.items[0].price);for(const v of ['-1','1.001']){el.value=v;await h.dispatch('input',el);}assert.equal(writes,1);assert.equal(h.ui.state.plans[0].items.at(-1).price,22.5);});
test('活动计算器只读到手价且没有满减或重复细则编辑',()=>{let s=seeded();s=R.save(s,'promotionSchemes',{name:'九折减五',steps:[{type:'discount',discount:9},{type:'reduction',amount:5}]});s.plans[0].promotionSchemeId=s.promotionSchemes[0].id;const h=appHarness(s),before=M.clone(s);h.ui.open('listing-calculator');const html=h.elements.get('#dialog').innerHTML;assert.match(html,/原始上架价/);assert.doesNotMatch(html,/满减|编辑方案/);assert.deepEqual(h.ui.state,before);});
