'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),N=require('../public/pricing-plan-model.js'),B=require('../public/pricing-prototype-model.js');
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);
function setup(){const s=N.seed(),p=s.plans[0];return {s,p};}
function second(s){const p=N.clone(s.plans[0]);p.id='plan-two';p.name='第二广告计划';s.plans.push(p);return p;}
const headers=['平台','店铺','平台商品名称','平台规格名称','平台商品ID','平台规格ID','平台售价','售卖状态','平台库存'];
function transfer(name,spec='MZJ90-3;40*60cm'){return N.transform([headers,['淘宝','店',name,spec,'p','s',19.9,'在售',8]],N.seed());}
test('v2 plans schema valid and JSON roundtrip',()=>{const s=N.seed();assert.ok(N.validState(s));assert.ok(N.validState(JSON.parse(JSON.stringify(s))));assert.equal(s.version,N.version);assert.equal(s.plans[0].shopId,s.shops[0].id);assert.equal(s.shops[0].rows,undefined);});
test('old prototype migration preserves settings rows and result/frame bytes',()=>{const old=B.seed(),h=B.makeRecord(old,old.shops[0].id,B.today()),frozen=JSON.stringify([h.result,h.frame]);const next=N.migrate(old);assert.equal(JSON.stringify([next.records[0].result,next.records[0].frame]),frozen);assert.deepEqual(next.plans[0].rows,old.shops[0].rows);assert.deepEqual(next.plans[0].settings,old.shops[0].settings);assert.ok(N.validState(next));assert.deepEqual(N.migrate(next),next);assert.equal(old.version,'pricing-prototype-1');});
test('migration rejects damaged legacy record before changing data',()=>{const old=B.seed();B.makeRecord(old,old.shops[0].id,B.today());old.records[0].result.gmv=123;assert.throws(()=>N.migrate(old),/校验/);});
test('400 gross minus 40 refund =360; ROI3.6, firstHour not double counted',()=>{const {s,p}=setup();p.settings.refundRates.firstHour=5;const r=N.calculate(s,p.id);near(r.gmv,400);near(r.refundAmount,40);near(r.refundGmv,360);near(r.refundRoi,3.6);near(r.paymentRoi,4);});
test('all three refund types count once',()=>{const {s,p}=setup();p.settings.refundRates={unshipped:5,shippedOnly:7,returnRefund:8,firstHour:10};const r=N.calculate(s,p.id);near(r.refundAmount,80);near(r.refundGmv,320);});
test('100 percent refund and zero spend do not create NaN',()=>{const {s,p}=setup();p.settings.refundRates.returnRefund=100;let r=N.calculate(s,p.id);assert.equal(r.refundGmv,0);assert.equal(r.refundRoi,0);p.settings.spend=0;r=N.calculate(s,p.id);assert.equal(r.gmv,0);assert.equal(r.refundRoi,null);assert.equal(r.paymentRoi,null);});
test('missing spend and invalid refund do not become zero forecasts',()=>{const {s,p}=setup();p.settings.spend='';assert.equal(N.calculate(s,p.id).gmv,null);p.settings.spend=100;p.settings.refundRates.returnRefund='';assert.equal(N.calculate(s,p.id).refundGmv,null);});
test('missing SKU mix does not erase independent GMV forecast',()=>{const {s,p}=setup();p.rows[0].share=0;const r=N.calculate(s,p.id);assert.equal(r.valid,false);assert.equal(r.profit,null);assert.equal(r.gmv,400);assert.equal(r.refundGmv,360);});
test('two plans independently track fees, settings and shares',()=>{const {s,p}=setup(),q=second(s);q.settings.spend=200;q.settings.actualRoi=2;q.settings.refundRates.returnRefund=20;q.rows[0].share=0;assert.equal(N.calculate(s,p.id).valid,true);assert.equal(N.calculate(s,q.id).valid,false);near(N.calculate(s,q.id).refundGmv,320);assert.equal(p.rows[0].share,20);});
test('shop ROI is ratio of sums, not mean of ROIs',()=>{const {s,p}=setup(),q=second(s);q.settings.spend=300;q.settings.actualRoi=2;q.settings.refundRates.returnRefund=20;const sum=N.shopSummary(s,p.shopId);assert.ok(sum.complete);near(sum.gmv,1000);near(sum.refundGmv,840);near(sum.refundRoi,2.1);near(sum.paymentRoi,2.5);});
test('incomplete plan blocks full aggregate and names missing plan',()=>{const {s,p}=setup(),q=second(s);q.settings.spend='';const sum=N.shopSummary(s,p.shopId);assert.equal(sum.complete,false);assert.equal(sum.gmv,null);assert.ok(sum.missing.includes(q.name));assert.equal(sum.plans[0].gmv,400);});
test('same shop date separate plans permitted, duplicate same plan rejected',()=>{const {s,p}=setup(),q=second(s);N.makeRecord(s,p.id,N.today());N.makeRecord(s,q.id,N.today());assert.throws(()=>N.makeRecord(s,p.id,N.today()),/本计划/);assert.ok(N.validState(s));});
test('record freezes all forecast metrics and follows plan, not active selection',()=>{const {s,p}=setup(),q=second(s);const h=N.makeRecord(s,p.id,N.today());const frozen=JSON.stringify(h);s.shops[0].activePlanId=q.id;p.settings.spend=999;s.strategies[0].stepPoints=2;assert.equal(JSON.stringify(h),frozen);assert.ok(N.validState(s));});
test('correction uses original cost snapshot and plan, preserves chain',()=>{const {s,p}=setup();const h=N.makeRecord(s,p.id,N.today());s.strategies[0].stepPoints=3;p.settings.fee=30;const temp=N.correctionState(s,h);temp.plans[0].settings.spend=120;const next=N.makeRecord(temp,p.id,N.today(),'',h.id,'修正消耗');s.records=temp.records;assert.equal(next.frame.plan.settings.fee,5);assert.equal(next.frame.strategies[0].stepPoints,1);assert.ok(N.validState(s));assert.equal(s.records[0].status,'superseded');});
test('v1 migrated snapshot can be corrected into v2 without rewriting original',()=>{const old=B.seed();const original=B.makeRecord(old,old.shops[0].id,B.today()),frozen=JSON.stringify(original.result);const s=N.migrate(old),h=s.records[0],temp=N.correctionState(s,h);N.makeRecord(temp,h.planId,N.today(),'',h.id,'修正旧记录');s.records=temp.records;assert.equal(JSON.stringify(s.records[0].result),frozen);assert.equal(s.records[1].snapshotVersion,2);assert.ok(N.validState(s));});
test('ledger plan date filter and trend include confirmed records only',()=>{const {s,p}=setup(),q=second(s);const a=N.makeRecord(s,p.id,'2026-09-01');N.makeRecord(s,q.id,'2026-09-01');N.makeRecord(s,p.id,'2026-09-02');a.status='void';const l=N.ledger(s,{shopId:p.shopId,planId:p.id,from:'2026-09-01',to:'2026-09-02'});assert.equal(l.rows.length,2);assert.equal(l.summary.count,1);assert.equal(l.points.length,1);assert.equal(l.points[0].date,'2026-09-02');near(l.summary.refundGmv,360);});
test('backup rejects bad plan refs and tampered derived GMV',()=>{const {s,p}=setup();const h=N.makeRecord(s,p.id,N.today());h.result.refundGmv++;assert.equal(N.validState(s),false);h.result.refundGmv--;h.planId='other';assert.equal(N.validState(s),false);});
test('new plans blank inputs and no rows, reusable strategies remain public',()=>{const {s,p}=setup();const q=N.newPlan(s,p.shopId);s.plans.push(q);assert.equal(q.rows.length,0);assert.equal(q.settings.spend,'');assert.equal(N.calculate(s,q.id).gmv,null);assert.ok(N.validState(s));});
test('cost ranks isolated between plans even identical group IDs',()=>{const {s,p}=setup(),q=second(s);p.groups[0].strategyId='rank';q.rows[0].weightGrams=10000;const a=N.calculate(s,p.id);assert.equal(a.rows[0].rank,1);assert.equal(a.rows[0].target,10);});
test('manual pricing and plan forecast not coupled by strategy changes',()=>{const {s,p}=setup();p.rows[0].priceMode='manual';p.rows[0].manualPrice=20;s.strategies[0].stepPoints=2;const r=N.calculate(s,p.id);assert.equal(r.rows[0].price,20);near(r.gmv,400);});
for(const name of ['伪亚麻','伪亚麻＋硅藻泥','伪亚麻＋亚麻'])test(name+' requires manual material',()=>{const r=transfer(name);assert.equal(r.rows[0].resolvedMaterial,'');assert.equal(r.rows[0].cost,'');assert.equal(r.rows[0].weight,'');assert.equal(r.summary.ready,false);assert.match(r.rows[0].issues[0].message,/伪亚麻可能/);assert.deepEqual(r.rows[0].candidates,['硅藻泥','亚麻']);});
test('pseudo linen in spec forces review even unique title material',()=>{const r=transfer('亚麻','伪亚麻 40*60cm');assert.equal(r.summary.ready,false);assert.equal(r.rows[0].resolvedMaterial,'');});
test('do not extend special word to 仿亚麻',()=>{const r=transfer('仿亚麻');assert.equal(r.rows[0].pseudoLinen,false);assert.equal(r.rows[0].resolvedMaterial,'亚麻');assert.equal(r.summary.ready,true);});
test('pseudo linen confirmation survives dimensions correction and keeps original name',()=>{let r=transfer('伪亚麻');r=N.reviewTransfer(r,[2],'硅藻泥');r=N.reviewTransfer(r,[2],'',{width:50,length:80});assert.equal(r.summary.ready,true);assert.equal(r.rows[0].resolvedMaterial,'硅藻泥');assert.equal(r.rows[0].materialSource,'manual');assert.equal(r.rows[0].values[3],'伪亚麻');assert.equal(r.rows[0].originalSpec,'MZJ90-3;40*60cm');assert.equal(r.rows[0].values[19],19.9);near(r.rows[0].area,.4);});
test('dimensions only cannot clear pseudo material ambiguity',()=>{const r=N.reviewTransfer(transfer('伪亚麻'),[2],'',{width:50,length:80});assert.equal(r.summary.ready,false);assert.equal(r.rows[0].cost,'');assert.equal(r.rows[0].resolvedMaterial,'');});
test('same link pseudo rows independently confirm two materials',()=>{const s=N.seed();let r=N.transform([headers,['淘宝','店','伪亚麻','40*60cm','p','s1',10,'在售',1],['淘宝','店','伪亚麻','40*60cm','p','s2',20,'在售',1]],s);r=N.reviewTransfer(r,[2],'硅藻泥');assert.equal(r.rows[1].resolvedMaterial,'');r=N.reviewTransfer(r,[3],'亚麻');assert.equal(r.summary.ready,true);assert.notEqual(r.rows[0].cost,r.rows[1].cost);});
for(const [raw,w,h] of [['MZJ90-3;40*60cm',40,60],['MZJ90-4;50*80cm',50,80],['款号M90-3；４０＊６０ＣＭ【吸水】',40,60],['厚3mm 40×60 数量2',40,60],['400mm x 60cm',40,60],['0.4m×0.6m',40,60],['40厘米乘60厘米',40,60],['40*60',40,60]])test('dimension '+raw,()=>{const r=N.dimensionCandidates(raw);assert.equal(r.ok,true);near(r.candidates[0].width,w);near(r.candidates[0].length,h);});
for(const raw of ['编号123 3mm 红色','MZJ90-3','40-60','40至60','40*60*3mm','ABC40X60','型号123','40*60cm / 50*80cm'])test('ambiguous/no dimensions '+raw,()=>assert.equal(N.dimensionCandidates(raw).ok,false));
test('equivalent repeated dimensions dedup after unit conversion',()=>{const r=N.dimensionCandidates('40*60cm / 400*600mm');assert.equal(r.ok,true);assert.equal(r.candidates.length,1);assert.equal(r.candidates[0].matches.length,2);});
test('multi-size manual material does not unlock dimensions or compute cost',()=>{let r=transfer('伪亚麻','40*60cm / 50*80cm');r=N.reviewTransfer(r,[2],'亚麻');assert.equal(r.summary.ready,false);assert.equal(r.rows[0].area,'');assert.equal(r.rows[0].weight,'');assert.equal(r.rows[0].cost,'');r=N.reviewTransfer(r,[2],'',{width:50,length:80});assert.equal(r.summary.ready,true);near(r.rows[0].area,.4);});
test('screenshot noise produces 0.24 not0.027 and correct exported static values',async()=>{const fs=require('node:fs'),path=require('node:path'),Excel=require('../public/assets/exceljs.min.js');const r=transfer('亚麻');assert.equal(r.summary.ready,true);near(r.rows[0].area,.24);const bytes=await N.exportProducts(fs.readFileSync(path.join(__dirname,'../public/assets/product-template.xlsx')),r),book=new Excel.Workbook();await book.xlsx.load(bytes);const sheet=book.worksheets[0];assert.equal(sheet.getCell('H2').value,'40*60');near(sheet.getCell('I2').value,.24);assert.equal(sheet.getCell('T2').value,19.9);});
test('pseudo material bulk selection rejects other materials atomically',()=>{const r=transfer('伪亚麻'),before=JSON.stringify(r);assert.throws(()=>N.reviewTransfer(r,[2],'水晶绒'),/硅藻泥或亚麻/);assert.equal(JSON.stringify(r),before);});
