'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {check}=require('../scripts/release-validation/check-release-acceptance.cjs');
test('formal release rejects pending manual evidence and mismatched installer evidence',t=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'mat-release-gate-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));
 fs.mkdirSync(path.join(root,'validation/candidate'),{recursive:true});fs.mkdirSync(path.join(root,'validation/acceptance'));
 const write=(p,d)=>fs.writeFileSync(path.join(root,p),JSON.stringify(d));
 write('package.json',{version:'1.2.18'});write('validation/candidate/sha256.json',{sha256:'a'.repeat(64)});
 const acceptance={version:'1.2.18',installerSha256:'a'.repeat(64),windows8GiB:{passed:false},windowsOffice:{passed:false}};
 write('validation/release-acceptance.json',acceptance);assert.throws(()=>check(root),/remains pending/);
 for(const key of ['windows8GiB','windowsOffice'])acceptance[key]={passed:true,evidence:'validation/acceptance/'+key+'.json'};
 write('validation/release-acceptance.json',acceptance);
 const common={passed:true,installerSha256:'a'.repeat(64),platform:'win32',checkedAt:'2026-09-30',method:'fixture'};
 write('validation/acceptance/windows8GiB.json',{...common,physicalMemoryGiB:16,physicalDevice:true});
 write('validation/acceptance/windowsOffice.json',{...common,application:'WPS',manuallyOpened:true,noRepairDialog:true,valuesAndLayoutVerified:true});
 assert.throws(()=>check(root),/8 GiB physical/);
 write('validation/acceptance/windows8GiB.json',{...common,physicalMemoryGiB:8,physicalDevice:true});assert.equal(check(root).passed,true);
 write('validation/acceptance/windowsOffice.json',{...common,installerSha256:'b'.repeat(64),application:'WPS',manuallyOpened:true,noRepairDialog:true,valuesAndLayoutVerified:true});assert.throws(()=>check(root));
});
test('approved CI scope preserves uncovered checks and is bound to this installer and version',t=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'mat-release-scope-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));
 fs.mkdirSync(path.join(root,'validation/candidate'),{recursive:true});fs.mkdirSync(path.join(root,'validation/acceptance'));
 const write=(p,d)=>fs.writeFileSync(path.join(root,p),JSON.stringify(d));
 const sha='beb86d1da519d04ed5a918f71f5ed5f5e106f9d9d4ceead7e0fc0af220f6e1c4';
 const approval={version:'1.2.19',installerSha256:sha,authorizedBy:'user',checkedAt:'2026-10-02',decision:'release-with-github-windows-ci',statement:'按 GitHub 验收发布，保留未覆盖说明',notCovered:['windows8GiB','windowsOffice']};
 const acceptance={version:'1.2.19',installerSha256:sha,releaseScope:{mode:'github-windows-ci',approval:'validation/acceptance/scope.json'},windows8GiB:{passed:false,evidence:null,status:'not-covered'},windowsOffice:{passed:false,evidence:null,status:'not-covered'}};
 write('package.json',{version:'1.2.19'});write('validation/candidate/sha256.json',{sha256:sha});write('validation/release-acceptance.json',acceptance);
 assert.throws(()=>check(root),/ENOENT/);
 write('validation/acceptance/scope.json',approval);assert.deepEqual(check(root).notCovered,['windows8GiB','windowsOffice']);
 acceptance.windowsOffice.passed=true;write('validation/release-acceptance.json',acceptance);assert.throws(()=>check(root),/must remain false/);
 acceptance.windowsOffice.passed=false;write('validation/release-acceptance.json',acceptance);
 approval.authorizedBy='assistant';write('validation/acceptance/scope.json',approval);assert.throws(()=>check(root));
 approval.authorizedBy='user';write('validation/acceptance/scope.json',approval);
 acceptance.installerSha256='b'.repeat(64);write('validation/candidate/sha256.json',{sha256:acceptance.installerSha256});write('validation/release-acceptance.json',acceptance);assert.throws(()=>check(root),/approved installer/);
 acceptance.installerSha256=sha;acceptance.version='1.2.20';write('validation/candidate/sha256.json',{sha256:sha});write('package.json',{version:'1.2.20'});write('validation/release-acceptance.json',acceptance);assert.throws(()=>check(root),/only for 1.2.19/);
});
