'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {chromium}=require(process.env.MAT_PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'../..'),M=require('../../public/domain.js'),R=require('../../public/reusable-rules.js'),W=require('../../public/workbook.js'),Excel=require('../../public/assets/exceljs.min.js');
const out=path.resolve(process.env.MAT_VERIFY_OUTPUT||'outputs/stage3');fs.mkdirSync(out,{recursive:true});
async function run(){
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'mat-stage3-')),installed=process.env.MAT_STAGE3_INSTALLED,label=installed?'native':'source';let server,child,browser,page,url;const errors=[],checks=[];
 let state=M.initialState();state.records=[];state.plans=[M.newPlan(state,state.shops[0].id,'隔离验收计划')];state.active=state.plans[0].id;state.activeShop=state.shops[0].id;
 state=R.addSizes(state,state.active,state.sizes.filter(s=>s.salesW===40&&s.salesH===60||s.salesW===50&&s.salesH===80).map(s=>s.id));
 const plan=state.plans[0];plan.items.forEach((i,n)=>Object.assign(i,{price:30+n*10,share:50,priceMode:'manual',productId:'000123',skuId:'0000'+n}));Object.assign(plan.params,{spend:100,actualRoi:5});assert.equal(M.validateBackup(state),true);
 try{
  if(installed){
   const {Store}=require('../../server/store.cjs'),store=new Store(dir);store.restore(state,store.read().revision,'synthetic-seed');store.close();
   const env={...process.env,MAT_DATA_DIR:dir,MAT_PORT:'4191'};delete env.ELECTRON_RUN_AS_NODE;child=require('node:child_process').spawn(installed,['--remote-debugging-port=9231'],{env,stdio:'ignore'});url='http://127.0.0.1:4191';
   const end=Date.now()+45000;while(true){try{const health=await(await fetch(url+'/api/health')).json();assert.equal(health.dataDir,dir);break;}catch(e){if(Date.now()>end)throw e;await new Promise(r=>setTimeout(r,200));}}
   browser=await chromium.connectOverCDP('http://127.0.0.1:9231');page=browser.contexts()[0].pages()[0];
  }else{server=require('../../server/index.cjs').createServer({port:0,dataDir:dir});server.store.restore(state,server.store.read().revision,'synthetic-seed');url=await server.listen();browser=await chromium.launch({channel:'chrome',headless:true});page=await browser.newPage();}
  page.setDefaultTimeout(20000);page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width:1440,height:950});await page.goto(url);await page.locator('[data-action=entry]').waitFor();await page.evaluate(()=>UiAppearance.setMotion(false));
  const click=a=>page.locator(`[data-action="${a}"]`).first().click(),saved=()=>page.waitForFunction(()=>document.querySelector('#save-status')?.dataset.status==='saved'),workspace=async()=> (await(await fetch(url+'/api/state')).json()).state;
  // Rules: invalid draft stays visible, successful save protects manual prices.
  await click('library-view');for(const tab of ['materials','sizes','shipping','pricingStrategies','sizeSchemes','promotionSchemes'])await page.locator(`[data-action=library-tab][data-tab="${tab}"]`).click();
  await page.locator('[data-action=library-tab][data-tab=pricingStrategies]').click();await click('new-reusable');await page.locator('[data-field=name]').fill('验收毛利');await page.locator('[data-field=margin]').fill('35');await click('save-modal');await page.locator('#dialog').waitFor({state:'hidden'});await saved();
  const strategy=(await workspace()).pricingStrategies.find(x=>x.name==='验收毛利');assert.ok(strategy);await click('plan-view');await page.locator('[data-plan-strategy]').selectOption(strategy.id);await saved();assert.deepEqual((await workspace()).plans[0].items.map(i=>i.price),[30,40]);
  await click('library-view');await page.locator('[data-action=library-tab][data-tab=materials]').click();await page.locator('[data-action=material][data-id="'+plan.materialId+'"]').click();const before=await workspace();const thickness=page.locator('[data-material-rule="0"][data-rule-key=thickness]');await thickness.fill('bad');await click('save-modal');await page.locator('#dialog-error').filter({hasText:'厚度需'}).waitFor();assert.equal(await thickness.inputValue(),'bad');assert.deepEqual(await workspace(),before);page.once('dialog',d=>d.accept());await click('close');checks.push('规则失败保留草稿与原数据，选择定价策略保护手动价');
  // Real drop, full aggregate and staged size; failed SaveQueue flush can retry.
  const book=new Excel.Workbook(),sheet=book.addWorksheet('销售');sheet.addRow(['商品SKU标题','商品成交订单数','商品成交件数']);for(const row of [['花色甲 40x60cm',3,30],['花色乙 60x40cm',7,70],['花色丙 50x80cm',20,200],['新尺寸 77x99cm',10,100]])sheet.addRow(row);
  await click('plan-view');await click('sku-options');await click('sales-import');await page.locator('[data-sales-period]').fill('2026-09-14 至 2026-09-20');
  await page.locator('[data-sales-upload-trigger]').evaluate((zone,bytes)=>{const dt=new DataTransfer();dt.items.add(new File([new Uint8Array(bytes)],'销售情况.xlsx',{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));zone.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:dt}));},[...Buffer.from(await book.xlsx.writeBuffer())]);
  await page.locator('[data-sales-map]').click();await page.locator('[data-sales-add-size]').click();await page.waitForFunction(()=>!document.querySelector('[data-sales-apply]')?.disabled);assert.equal((await workspace()).plans[0].items.length,2);
  const stateRoute='**/api/state';await page.route(stateRoute,r=>r.request().method()==='PUT'?r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'隔离测试保存失败'})}):r.continue());
  await page.locator('[data-sales-apply]').click();await page.locator('.sales-import-alert').filter({hasText:'尚未保存成功'}).waitFor();assert.equal((await workspace()).plans[0].items.length,2);await page.unroute(stateRoute);await page.locator('[data-sales-apply]').click();await page.locator('[data-sales-undo]').waitFor();await saved();
  let s=await workspace();assert.equal(s.plans[0].items.length,3);assert.deepEqual(s.plans[0].items.map(i=>i.sales),[10,20,10]);assert.deepEqual(s.plans[0].items.map(i=>i.share),[25,50,25]);assert.equal(s.plans[0].items[0].skuId,'00000');
  await page.locator('[data-sales-undo]').click();await page.waitForFunction(()=>document.querySelector('.sales-import-notice')?.textContent.includes('已撤销'));await saved();assert.equal((await workspace()).plans[0].items.length,2);assert.equal((await workspace()).sizes.some(x=>x.salesW===77&&x.salesH===99),false);
  await page.locator('[data-sales-add-size]').click();await page.waitForFunction(()=>!document.querySelector('[data-sales-apply]')?.disabled);await page.locator('[data-sales-apply]').click();await page.locator('[data-sales-undo]').waitFor();await page.locator('[data-sales-close]').first().click();await saved();checks.push('拖放销量按尺寸合并、暂存新尺寸、保存失败重试、撤销和重新应用');
  // Posting once despite save failure, then correcting without touching the snapshot.
  await click('entry');await page.locator('[data-entry-param=actualGmv]').fill('800');await page.route(stateRoute,r=>r.request().method()==='PUT'?r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'隔离入账保存失败'})}):r.continue());await click('confirm-record');await page.locator('#dialog-error').filter({hasText:'尚未写入数据库'}).waitFor();assert.equal((await workspace()).records.length,0);await page.unroute(stateRoute);await click('confirm-record');await page.locator('#dialog').waitFor({state:'hidden'});await saved();s=await workspace();assert.equal(s.records.length,1);assert.equal(s.records[0].result.gmv,800);const frozen=M.clone(s.records[0]);
  await click('record-detail');await click('correct-record');await page.locator('[data-field=reason]').fill('隔离核对');await page.locator('[data-entry-param=actualGmv]').fill('900');await click('confirm-record');await page.locator('#dialog').waitFor({state:'hidden'});await saved();s=await workspace();assert.equal(s.records.length,2);assert.deepEqual(s.records[0].frame,frozen.frame);assert.deepEqual(s.records[0].result,frozen.result);assert.equal(s.records[0].status,'superseded');assert.equal(require('../../public/operating-records/queries.js').summary(s).gmv,900);
  await click('ledger-view');await page.locator('[data-action=operating-group][data-group=records]').click();await page.locator('[data-filter=includeOld]').check();await page.screenshot({path:path.join(out,`stage3-ledger-${label}.png`)});checks.push('入账保存失败重试不重复，更正保留原金额与成本，总账只计有效版本');
  // Backup through the actual worker and UI, decode all business data, then restore.
  await click('export');const pendingDownload=page.waitForEvent('download');await click('confirm-export');const download=await pendingDownload;const exportPath=path.join(out,`stage3-backup-${label}.xlsx`);await download.saveAs(exportPath);const restored=await W.importWorkbook(await fs.promises.readFile(exportPath));assert.deepEqual(restored,s);
  await click('data-view');await page.locator('#backup-input').setInputFiles(exportPath);await page.locator('[data-action=confirm-restore]').waitFor();await click('confirm-restore');await page.locator('#dialog').waitFor({state:'hidden'});await saved();assert.deepEqual((await workspace()).records,s.records);await page.reload();await page.locator('[data-action=entry]').waitFor();assert.equal((await workspace()).records.length,2);checks.push('实际备份任务、Excel 回读、合并恢复和重启读取一致');
  // Mount/unmount around product module with unchanged workspace.
  const stable=await workspace();await click('product-view');await page.locator('[data-pv4-file]').waitFor();await click('library-view');await click('product-view');await page.locator('[data-pv4-file]').waitFor();assert.deepEqual(await workspace(),stable);await page.screenshot({path:path.join(out,`stage3-shell-${label}.png`)});checks.push('商品模块切页重新挂载不改工作区');assert.deepEqual(errors,[]);
  const report={passed:true,label,isolatedData:true,checks,browserErrors:errors,executable:installed?path.resolve(installed):null,payloadHash:installed?require('node:crypto').createHash('sha256').update(fs.readFileSync(path.resolve(path.dirname(installed),'../Resources/app.asar'))).digest('hex'):null};fs.writeFileSync(path.join(out,`stage3-${label}.json`),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
 }catch(error){fs.writeFileSync(path.join(out,`stage3-failure-${label}.json`),JSON.stringify({error:String(error),errors,text:await page?.locator('body').innerText().catch(()=>''),dir},null,2));if(page)await page.screenshot({path:path.join(out,`stage3-failure-${label}.png`)});throw error;}
 finally{if(child){child.kill();await new Promise(resolve=>{if(child.exitCode!==null||child.signalCode!==null)return resolve();const timer=setTimeout(()=>child.kill('SIGKILL'),5000);child.once('exit',()=>{clearTimeout(timer);resolve();});});}await browser?.close();await server?.close();fs.rmSync(dir,{recursive:true,force:true,maxRetries:10,retryDelay:200});}
}
run().catch(e=>{console.error(e);process.exitCode=1;});
